### PR TITLE
Fix build (1F7D9 merge broke build)

### PR DESCRIPTION
**Pull request by LaPingvino**
I tested that this fix makes the font build correctly locally, not 100% sure about the full pipeline but that test is running on my fork as we speak.

### CODE REVIEW

**Comment by LaPingvino** [comment]
Don't merge yet, there are still issues (font doesn't include new file correctly)

**Comment by LaPingvino** [comment]
Okay, the issue at the moment is that when built with everything but the last commit, it builds but doesn't include the character, with the last one it gives an error message when trying to build the font (the only change is the layer id).

@ctrlcctrlv I guess we could say you warned about this xD

**Comment by ctrlcctrlv** [comment]
sure did

why would the layer id even update :thinking: 

in any event, i don't thnk this will be accepted because isn't this a varfont? i think u need to add two new glyphs?

maybe you did and i just dunno how to read it. :-)

**Comment by ctrlcctrlv** [comment]
oh i see this is to fix a broken build due to the merger of #66. well in that event it should be merged even  if it has the problem that i said , or if the potential problem i brought up is seen as serious enough #66 (sigh) reverted.

**Comment by simoncozens** [comment]
Thanks for this; I was planning just to fix it. @ctrlcctrlv, this doesn't need two glyphs, Symbols2 is one weight only.

I don't know why the CI doesn't run on pull requests. I've tried to get it, but it just doesn't. If anyone wants to spend time thinking about that I would very much appreciate it.

**Pull request merged**
